# Generated by Django 5.0.3 on 2024-03-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='age',
            field=models.CharField(blank=True, choices=[(3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18')], default='3', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='detailed_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='difficulty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='max_players',
            field=models.CharField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default='1', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='min_players',
            field=models.CharField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default='1', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='play_time',
            field=models.CharField(blank=True, choices=[(15, '15'), (30, '30'), (45, '45'), (60, '60'), (90, '90'), (120, '120'), (150, '150'), (180, '180')], default='15', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='year_published',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
